# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d108b3684135f78c3c5e8059e9e234d11b21f0cb62ef50bf7ee0f1a775c1693af00e86b529369e15a07b79d0412e1c6d184adbab3c54f2a2d6acf0ba187940c4

test:
  secret_key_base: 0286594c478437482229c038aef94f2860f6a17900016fe2a729716e28d9a3a0604e9516b1c6f8d40a7ccc87dda9e49dfa29688e48b694ed0f2e1d37c219aed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
